### PR TITLE
add distTar task to build distribution tar file (with plugin jar and external runtime dependency jars)

### LINKED ISSUE #30: plugin deployment needs tar of 3 jars as jenkins artifact
See SAR-3198.

### PR DESCRIPTION
**Pull request by jmartin-sul**
- lib/runtime/: new directory to contain runtime dependency jars (google guava for URL escaping and apache commons validator for IP address validation, to start)
- build.gradle
  - add the distribution plugin
  - configure default distribution to contain the SulWowza plugin jar and its runtime dependencies
  - remove the explicit guava and commons-validator dependencies now that the jar files are in lib in the repo

closes #30

### CODE REVIEW

**Comment by jmartin-sul** [comment]
as per the plugin default, the tar file is output to `build/distributions/dlss-wowza-v*.tar` (name is picked up automatically by the similar machinery to what sets the jar name, i assume).  the tar will have three sibling jar files in its root (the plugin jar, the guava jar, and the commons validator jar).  the two external dependencies both have their versions because i kept the version number in the filename when adding them to the repo.  the dlss wowza plugin jar will have the version number because that jar comes from the existing `deploymentJar` task, which sets up naming.  as a side-effect of that, `distTar` only works for the strict `deploymentJar` mode at the moment.  so `distTar` only works on properly tagged versions.  i can look into a relaxed mode, if people think that'd be worth the effort.

**Comment by jmartin-sul** [comment]
if this gets merged, i think what remains is:
- update jenkins config to run the `distTar` task instead of `deploymentJar`
- update the jenkins config to grab the tar file instead of the jar file (from `build/distributions/dlss-wowza-v*.tar`)
- configure puppet to do whatever magic is needed to unpack the tar file and replace the old versions of the jar files

**Comment by jmartin-sul** [comment]
relevant gradle documentation:  https://docs.gradle.org/current/userguide/distribution_plugin.html

**Comment by ndushay** [comment]
This looks great.  I like that you versioned the guava and validator jars.  I think the name of the output is fine.

I tried to run `.gradlew distTar` but it failed due to versions, which is expected, I suppose.  Do you assert the tar file created has the 3 jars in it, since I can't easily check?

I don't think it's worth the effort to do something about the relaxed version mode.

**Comment by ndushay** [comment]
Merged it and confirmed it worked afterwards.   Updated the jenkins build to build the tar, and it works.  SAR-3198 has the details of what needs to happen to puppet code.

**Comment by jmartin-sul** [comment]
awesome, thanks @ndushay!

**Pull request merged**
